### ISSUE TITLE
update docs on master for 1.9 release checklist

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3081]
This is just a checklist to help me keep track of all the docs changes per updates in the cookiecutters.

See #3042, #3048, #3052.

Modify the `src` files:
- [x] #3042 `docs/` search for `config.include('pyramid_tm')`, replace with:
  ```
      config.include('pyramid_tm')
      config.include('pyramid_retry')
  ```
- [x] #3059 `docs/` search for `config = Configurator(settings=settings)`, replace with:
  ```
      config = Configurator(settings=settings)
      settings = config.get_settings()
      settings['tm.manager_hook'] = 'pyramid_tm.explicit_manager'
  ```
- [x] #3059 `docs/` search for `config = Configurator(root_factory=root_factory, settings=settings)`, replace with:
  ```
      config = Configurator(root_factory=root_factory, settings=settings)
      settings = config.get_settings()
      settings['tm.manager_hook'] = 'pyramid_tm.explicit_manager'
  ```
- [x] #3059 `docs/` search for `settings = config.get_settings()`, for only those that are not duplicates of previous two items, replace with:
  ```
      settings = config.get_settings()
      settings['tm.manager_hook'] = 'pyramid_tm.explicit_manager'
  ```

Modify the `.rst` files:
- [x] `docs/` regex for `literalinclude.*setup.py` found 21 matches in 16 files
- [x] `docs/tutorials` regex for `literalinclude.*__init__.py` found 20 matches in 5 files
- [x] `docs/` search for:
  ```
  requires = [
    'pyramid
  ```

**Comment by stevepiercy** [comment]
I went a different angle by just replacing the src files first, then walking through each of the tutorials and narrative docs that referred to any usage of cookiecutters.

This is now all done, awaiting review in PR #3082
